---

play_services:
  yum:
    - name: git
      state: latest
    - name: make
      state: latest
    - name: go-toolset
      state: latest
  make_from_git:
    - url: https://github.com/BastienBalaud/golang-myip.git
      name: golang-myip
      binary_path: build/server.x86_64
      serviceTemplate: golang-myip.j2
  service:
    - name: firewalld
      enabled: yes
      state: started
    - name: golang-myip
      enabled: yes
      state: started

play_users:
  - name: htomasi
    group: student
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH69bImSyoVQrjfqYS5KxwXWN+8ENLXt1vihAw7tDhdH hugotomasi@Hugos-MacBook-Air.local"
    sudo_conf: "ALL = (ALL) PASSWD:ALL"
  - name: bbalaud
    group: not_student
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAmM7WeoXFKZGnDLV8RA3jfeYKPIYzTNIe3Yqr7Z11BV hurrycane@rocinante_ed%"
    sudo_conf: "ALL = (ALL) NOPASSWD:ALL"
  - name: jmichu
