---

- name: install package with dnf
  dnf:
    name: "{{ item.name }}"
    state: "{{ item.state | default('latest') }}"
  loop: "{{ list_services.dnf }}"
  loop_control:
    label: "{{ item.name }}"
  when: list_services.dnf
  become: True
  tags: package

- name: enable service
  systemd:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled | default(False) }}"
    state: "{{ item.state | default('stopped') }}"
  loop: "{{ list_services.service }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - list_services.service
    - item.enabled
  become: True
  tags: package